language: node_js
node_js:
- "4.1.0"
before_install:
- "cp /home/travis/.meteor/packages/meteor-tool/1.1.9/mt-os.linux.x86_64/scripts/admin/launch-meteor /usr/bin/meteor"
- "curl -L http://git.io/ejPSng | /bin/sh"